package exceptions_and_error_handling;

import java.util.Arrays;
import java.util.Scanner;

public class NumberInRange {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        int[] range = Arrays.stream(scanner.nextLine().split("\\s+"))
                .mapToInt(Integer::parseInt).toArray();

        int start = range[0];
        int end = range[1];

        System.out.printf("Range: [%d...%d]\n", start, end);
        boolean isWithinRange = false;
        int number;

        while (!isWithinRange) {
            String line = scanner.nextLine();
            try {
                number = Integer.parseInt(line);
                isWithinRange = number >= start && number <= end;
                if (isWithinRange) {
                    System.out.println("Valid number: " + number);
                    return;
                }

            } catch (NumberFormatException ignored) {
            }

            System.out.println("Invalid number: " + line);

        }
    }
}
